### ISSUE TITLE
Yield generator spamming up the income statement with headings

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#122]
Every time the irc bot reconnects it will add a line of headings to the income statement csv file. https://github.com/chris-belcher/joinmarket/blob/master/yield-generator.py#L48

Instead it should check whether the file exists and only add the headings the first time it's created.

Also, if the bot is running under testnet it SHOULD NOT log coinjoins to file.

**Comment by veox** [comment]
This issue is still listed [https://github.com/chris-belcher/joinmarket/wiki/What-can-I-do-for-JoinMarket%3F](on the Wiki).

Suggestion: use github issue tracker tags and link to those instead.

**Comment by chris-belcher** [comment]
thanks

agreed thats not a bad idea
