### ISSUE TITLE
wallet class abstraction

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#13]
Right now the taker class requires a wallet class, when it really only needs access to the private keys of its own addresses in order to sign, and a function for finding the address and value of a utxo.
So there needs to be an abstract superclass which just has get_key_from_addr(self, addr). The class can be called AddressToKeyMapping or something.
This will be useful for when eventually making the electrum plugin, taker class will just need private keys that electrum gives it.

**Comment by chris-belcher** [comment]
also the managing-internal-addresses functionality can be seperated from the querying-the-blockchain functionality, this will probably be important when coding other methods to query the blockchain such as connecting to bitcoind json_rpc.

**Comment by AdamISZ** [comment]
I'm not sure that separating `get_key_from_addr` from the rest of the Wallet functionality is so important (although for sure not saying it's wrong); it seems more that you want a Wallet interface that is implemented either by Electrum or by other code. 


I think the overarching structure is something like : an interface for key management wallet features, and a separate interface for blockchain query features. Both could be addressed by one external dependency (e.g. Electrum) or they could use different implementation layers, e.g. blockchain access implemented through bitcoind and key management implemented within JoinMarket code.

**Comment by chris-belcher** [comment]
Read through all the CoinJoinTX code, I've decided we probably dont need the abstract superclass.

For the electrum plugin, the wallet.unspent and wallet.addr_cache dictionaries can just have the values inserted in them. Then the CoinJoinTX should work without editing.
