### ISSUE TITLE
Use JSON-RPC for Bitcoin Core interface

### ISSUE THREAD

**Issue by domob1812** [chris-belcher/joinmarket#137]
Currently, the Bitcoin Core interface uses the CLI binary.  Instead, one could use JSON-RPC directly.  It is not hard to implement directly, or an existing library like http://json-rpc.org/wiki/python-json-rpc could be used.  This is probably more efficient than using the CLI binary.  In addition, it is easier to handle errors in a clean way, as the error codes are readily available.

Is this desired, or was the CLI method chosen for a specific reason?  If a switch to JSON-RPC is considered a good idea, I can provide a patch.

**Comment by chris-belcher** [comment]
It is a good idea. I did think about it once but didn't get a chance to open the issue.

I don't know the reason the CLI binary was chosen, we should ask @AdamISZ if there's any reason against.

**Comment by AdamISZ** [comment]
No reason at all; I didn't even think about it. Thanks for the suggestion @domob1812 , sounds good.

**Comment by adlai** [comment]
python-json-rpc is for the service... you want the brilliantly named client library, https://pypi.python.org/pypi/python-jsonrpc

**Comment by domob1812** [comment]
I've already interfaced to Bitcoin (and Namecoin) via from multiple languages - and in the beginning, I did it also with the CLI binary.  However, since I switched to JSON-RPC for those projects, I like it better.

Is it ok to introduce a dependency on the JSON-RPC library?  I also have code that implements a simple JSON-RPC client itself using the HTTP standard library of Python.  I can do whatever you think is better.  Using the JSON-RPC library is, of course, simpler and introduces less additional code.  On the other hand, I recall that it is not so easy to give a "nice" error message when the user's configured credentials are wrong.  Not sure if that's a big issue.

**Comment by adlai** [comment]
@domob1812 I vote for reusing your code wrapping the standard HTTP client, as that enables socket reuse and avoids dependency bloat.

**Comment by chris-belcher** [comment]
Using your own http json-rpc library seems the best. The only downside might be more debugging is required since the library is so new. But json-rpc is quite a simple protocol so it probably wont be a problem.

JoinMarket already uses a custom made IRC library instead of having as a dependency one of the libraries already written.

**Comment by chris-belcher** [comment]
Making it easier to handle errors in a clean way is related to #132

**Comment by domob1812** [comment]
See https://github.com/chris-belcher/joinmarket/pull/141.

**Comment by fivepiece** [comment]
Saw #141 now,
Does joinmarket need that kind of elevated access to Core?
Maybe it'll be better to use the REST interface?

**Comment by domob1812** [comment]
@fivepiece At least for `--rpcwallet`, joinmarket needs access to the wallet and, among others, `dumpprivkey`.  Thus we need JSON-RPC.  It may be possible to use the REST interface if `--rpcwallet` is not used.  I've also already worked with the REST interface, and could adapt my patch to include *both* options.  This makes the code more complicated, of course, but may allow to use Bitcoin Core only over REST if `--rpcwallet` is not used.  What do others think?

**Comment by chris-belcher** [comment]
I hadn't heard of REST until now.
It looks useful, it could be added as another BlockChainInterfaace subclass. It could be good for separating privileges but fact is JoinMarket already has your private keys so it's a very trusted process regardless.

**Comment by chris-belcher** [comment]
#141 has been merged.

**Comment by chris-belcher** [comment]
Would there be any significant benefits right now to socket reuse with json-rpc? Maybe the importing of watch-only addresses would go faster.
