### ISSUE TITLE
Cannot access ob-watcher.py from other computer

### ISSUE THREAD

**Issue by btcspry** [chris-belcher/joinmarket#138]
I think there's something blocking access from viewing ob-watcher.py from another computer on the same network.

**Comment by chris-belcher** [comment]
it binds to localhost by default

using the command line option -H to make it bind to another address to accept connections from there, for example the empty string "" which makes it accept from any address.

added here https://github.com/chris-belcher/joinmarket/pull/126

**Comment by btcspry** [comment]
Great, thanks!
