### ISSUE TITLE
"Input/output error" when running yield-generator as background process on a server

### ISSUE THREAD

**Issue by domob1812** [chris-belcher/joinmarket#142]
I want to run a yield generator on my VPS.  When I start it there from a terminal session, everything is fine and I have confirmed that I can finalise joins with it.  However, when I start the process in the background (with `&` character on the shell or by using Ctrl+Z and `bg`), it does not work anymore as soon as I log out of the terminal session.  The process keeps running and even responds to orderbook requests, but initiating a join with it fails.  The debug log then shows these lines:

    [2015/07/07 20:43:20] <<pubmsg nick=KelySuppo message=!orderbook
    [2015/07/07 20:43:31] <<privmsg nick=KelySuppo message=!fill 0 20000000 9689dd5ce1dbc0019131124e9c3634a1bcde3e6960640ec84c305ef547080617
    [2015/07/07 20:43:31] new cjorder nick=KelySuppo oid=0 amount=20000000
    [2015/07/07 20:43:31] IOError(5, 'Input/output error')
    [2015/07/07 20:43:31] disconnected irc
    [2015/07/07 20:44:01] connecting
    [2015/07/07 20:44:01] Successfully authenticated
    [2015/07/07 20:44:02] Connected to IRC and joined channel

Of course, this may be an issue with the way the VPS handles my terminal sessions rather than a bug with JoinMarket.  But I think this behaviour is really strange, and I think that it is absolutely vital to be able to run a maker on a VPS process.

**Comment by K1773R** [comment]
just use screen ;)

**Comment by CohibAA** [comment]
agreed, screen solves this issue

**Comment by domob1812** [comment]
Cool, learned another thing!  Seems to work now, although I will only be able to test an actual join later today.  Thanks!

Should this be closed then, or should we still try to find the reason and fix it?  Apart from joinmarket, I've never had problems with running daemon processes in the background even without screen.

**Comment by adlai** [comment]
Joinmarket needs a responsive output. You could try editing the code so ```common.debug``` only logs, without printing.

**Comment by chris-belcher** [comment]
[2015/07/07 20:43:31] IOError(5, 'Input/output error')

This indicates the error has been caught by a try: except: block.
It is slightly unfortunate it hasn't printed out the stack trace, that could be added in.
