### ISSUE TITLE
JoinMarket vulnerable to Double split? Sing message?

### ISSUE THREAD

**Issue by lojadaantu** [chris-belcher/joinmarket#144]
Hi Belcher,

How are you?

I found JoinMarket and I loved it, congrats. I would be thankful if you could answer a few questions.

1) I saw a chart with name of wallets of investors and values. Where is it available?

2) Is there a way to see how many coins are happening per day or hour and average value?

3) Really idiot question, but I see the transactions are with internal wallet, what is the benefit? I mean, internal transactions are not public, right? 

4) If we could recover the whole wallet and money with the key, it means that my coins are not with me, instead they are on a third-party server, right? What means if someone hack this system? I mean, what security do we have?

5) In practice, have someone tried to track the coins joined? How hard was it? Was possible?

6) Have you see this issue? https://bitcoin.org/en/alert/2015-07-04-spv-mining

Is JoinMaker vulnerable? 

7) Is there a way to sign message with JoinMarket?

Thanks.

**Comment by chris-belcher** [comment]
I have answered here. It is a more appropriate place for question like this (what does this do? how do I do this?) than the github issue tracker https://bitcointalk.org/index.php?topic=919116.msg11840730#msg11840730

**Comment by lojadaantu** [comment]
Hi Chris,

Thanks so much, very appreciated. And sorry for too much dumb questions.

If you don't mind I would like to ask your assistance there again, I have
tons of doubts still about it and the whole process. I know I'm being a
pain and I apologize about it, but on the other hand I think it could be
good to your project because other persons will read and likely adopt it as
I expect to do. :)

https://bitcointalk.org/index.php?topic=919116.msg11848933#msg11848933

Thanks.
