### ISSUE TITLE
Negative earnings from new-yieldgen-algo

### ISSUE THREAD

**Issue by tailsjoin** [chris-belcher/joinmarket#146]
I earned negative amounts twice while using the new-yieldgen-algo branch. I have logs if you'd like. I just don't want to post them here.

**Comment by chris-belcher** [comment]
Can you post the line where your bot announces orders, and then post the lines with !fill which tells us the amount being coinjoined

**Comment by tailsjoin** [comment]
Pubkey ID please.

**Comment by chris-belcher** [comment]
fixed here https://github.com/chris-belcher/joinmarket/commit/e0ab8ae69b047eb4a50c5f56225eeeb080aa40de
