### ISSUE TITLE
sweeping a mixing depth with sendpayment.py doesn't work

### ISSUE THREAD

**Issue by cqv2** [chris-belcher/joinmarket#168]
I've tried to sweep a mixing depth to move the balance to another wallet file. First you have to create a transaction without submitting it to get to know the fee (using the -C option to get the same result in the next step). Next you have to run sendpayment.py with the full amount minus tx fee and minus the cj fee. The bug here is that an empty output is created and the transaction wouldn't be accepted.
The output:
failed blockr.io pushtx
pushed tx None
unable to pushtx
line was zero length

My current workaround:
You'll have to subtract at least one satoshi to create a valid tx output. The transaction is still rejected by the blockr api but it works on other pushtx services. Just copy and paste the raw tx from the console to e.g. https://blockchain.info/pushtx .

**Comment by chris-belcher** [comment]
Ideally you would share the debug log so we can see in detail exactly what happened. Right now with this OP there's no chance of fixing whatever the bug is.

I have an email and PGP key to improve privacy. Although you're already telling blockr.io everything by using them instead of your own Bitcoin Core.

**Comment by cqv2** [comment]
What happens is that sendpayment.py is trying to broadcast a tx which sends 0 satoshi to a change address. A zero satoshi output is not accepted by the bitcoin nodes. This is not a critical bug but I think it should be noted somewhere.

**Comment by chris-belcher** [comment]
Thanks for the reply.

That's interesting. According to the relevant part of the code for sendpayment.py, a sweep transaction has no change address https://github.com/chris-belcher/joinmarket/blob/master/sendpayment.py#L49-L63
You can see it passes None as the change parameter.

Does the debug log show it choosing sweep orders or choosing regular orders? Sweep order choosing is when it calculates the highest possible coinjoin amount as well as choosing which makers to join with.

**Comment by cqv2** [comment]
There is a sweeping function? Good to know!
I did manually calculate the right amount for a sweep. Typing in zero would have been easier. So this can be deleted, there are more important things.

**Comment by chris-belcher** [comment]
haha :)

**Comment by cqv2** [comment]
Yes, it's unconfirmed since yesterday. This could be called a bug since the maker's coins are still blocked. How long will it take until something happens?

**Comment by chris-belcher** [comment]
Noted.

There's a couple of DOS opportunities like this. They're slowly being closed but until then we just keep an eye out. JoinMarket doesnt work in theory but works in practice. You might be surprised how long we can go before someone bothers to attack the project in this way. It won't even do that much damage and it's not really profitable.

**Comment by cqv2** [comment]
I agree with you. At this point there is one wouldn't achieve anything by harming joinmarket. 
My question was, how long will it take until the transaction disappears or confirm?

**Comment by adlai** [comment]
It could stick around in mempools for over a week. The quickest way to kill it is by double spending.
