### ISSUE TITLE
Watchonly addresses not imported to bitcoind, requiring unnecessary rescan after long-running yield generator

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#175]
If the yield generator is running with json-rpc blockchain interface and generating many new addresses, it will eventually use addresses that were not imported. Then next time it is started the sync_addresses() will not find them and ask the user to -rescan, which would be completely unnecessary because they are already known to be empty or with transactions that were already handled by bitcoin core.

It's not clear right now exactly where this check should be added. Either in oid_to_order() and the tumbler.py equivalent or to wallet.get_new_address()

**Comment by CohibAA** [comment]
This seems to be the output in this situation:

> [2015/08/28 xx:xx:xx] requesting wallet history
[2015/08/28 xx:xx:xx] rpc: getaddressesbyaccount ['joinmarket-wallet-xxxxxx']
[2015/08/28 xx:xx:xx] rpc: listtransactions ['joinmarket-wallet-xxxxxx', 1000, 0, True]
[2015/08/28 xx:xx:xx] too few addresses in [(x, x)]
[2015/08/28 xx:xx:xx] importing 150 addresses into account joinmarket-wallet-xxxxxx
now restart bitcoind with -rescan

This terminates the yield-generator bot script.  The yield-generator script can safely be started again without actually restarting bitcoind with -rescan as long as the maker is using bitcoin-rpc, correct?

**Comment by chris-belcher** [comment]
Not correct. You will need to restart.

As your yield generator was running it didn't add new watchonly addresses, now you've restarted it noticed and added them. -rescan will find which UTXOs are yours so you'll need to do it so your yield generator knows how much bitcoin it has.

**Comment by adlai** [comment]
Obsessively running wallet-tool every few minutes/days will importaddress each new batch early enough to track all your coins without pausing to rescan (source: experience).

Another option is to [omit rescan suppression](https://github.com/bitcoin/bitcoin/blob/ddd8d8/src/wallet/rpcdump.cpp#L211-L239) from the [last importaddress call](https://github.com/chris-belcher/joinmarket/blob/fc2e58/lib/blockchaininterface.py#L437).

**Comment by chris-belcher** [comment]
If you're importing a completely new address you won't need to rescan at all.

**Comment by chris-belcher** [comment]
https://github.com/chris-belcher/joinmarket/pull/241
