### ISSUE TITLE
Wallet file hash changes.

### ISSUE THREAD

**Issue by tailsjoin** [chris-belcher/joinmarket#190]
I found something interesting today. I don't know if you remember, but one day in the irc I said that the hash on my wallet had changed out of nowhere, and it was asking me to rescan. Well I did rescan that day. For some reason, after the rescan the wallet hash went back to it's original and I moved on with my life. Well since then this same thing has randomly happened to me again and again, but I never rescanned. I just try three, four times until it gets right or I recover from seed.

Here's where things get interesting. I got a walletnotify twice today that my maker was not waiting on. The first came immediately after a JM tx so I ignored it, but the second came when all was quiet and it was for 1.5btc! So I opened up qt and saw that it was from this wallet that I accidentally created that day in the irc . So someone else is using this wallet and I'm watching all of their transactions currently.

![](https://infotomb.com/5tshc.png)

First I checked that it wasn't watching only funds I had forgotten about in an old wallet, but I have never deleted one and I have all the seeds I've ever created with JM. I painstakingly went through all of my wallet files to make sure  I'm not sharing a wallet with someone, and I definitely do not have that wallet hash. Maybe someone has a log from irc to check. Somewhere around the middle of July I think.

In playing with the wallets I found that if you enter an incorrect password for your wallet file sometimes it will accept the incorrect (or even blank on some wallet files) password and create a wallet using that as a seed. You can recreate it with the same incorrect password that worked and it will make the same wallet again. It will not make the original wallet unless you provide the correct passphrase, but sometimes even with the correct passphrase a new wallet is generated. I'm very sure of this because I use a password manager, and I don't even know what my passphrases are. I just copy/paste.

**Comment by AdamISZ** [comment]
It seems like there's a lot going on here. With regard to:

> In playing with the wallets I found that if you enter an incorrect password for your wallet file sometimes it will accept the incorrect (or even blank on some wallet files) password and create a wallet using that as a seed. 

Do you ever use testnet? (I only ask because that's expected behaviour there). More importantly, which command are you running here? yieldgen, sendpayment, wallet-tool or tumbler?

**Comment by AdamISZ** [comment]
@tailsjoin  Please see #191 . I believe this is probably a big contributory factor to what you saw, although there's a good chance it's not the total explanation.

**Comment by tailsjoin** [comment]
I have seen the hash change on yield-generator and wallet-tool. Yesterday was wallet-tool. 

It seems https://github.com/chris-belcher/joinmarket/pull/191 is the problem for throwing an incorrect hash when the password is incorrect.

**Comment by tailsjoin** [comment]
I have never used testnet. I have had the wallet file change on sendpayment and wallet-tool. Yesterday was wallet tool.

**Comment by AdamISZ** [comment]
Well, I guess #191 explains that part, but I'm not sure that it could explain the part about you getting notified of transactions that weren't yours.. superficially, that seems like it shouldn't be possible? Bit of a headscratcher. The seeds are supposed to be from os.urandom().

**Comment by AdamISZ** [comment]
@tailsjoin I have found out the issue. It is (as you probably suspected!), a serious bug, albeit it requires pretty insane user input. I'm taking preventive measures; once they're complete I'll explain in detail. And submit a PR ASAP.

**Comment by AdamISZ** [comment]
Update: https://www.reddit.com/r/joinmarket/comments/3h0vyy/alert_someone_sent_coins_to_and_has_been_using_a/

**Comment by tailsjoin** [comment]
Good find. I'm still interested to see if someone has logs from irc that they can grep for that wallet has around early to mid july and see if I generated it after a recover. I'm pretty sure I ended up with that seed after a sendpayment or wallet-tool, but I could be wrong.

**Comment by AdamISZ** [comment]
wallet-tool.py recover : according to me that's the only way it can happen. I also got the same wallet hash of course. The things I'm curious about are: were you running recover from a script (perhaps to avoid having to store wallet files)? That might be a natural way that it could happen, it's less likely that you would manually just press "Enter". And, just for clarity: you're sure you didn't fund any of the coins in that wallet?

It's going to be tricky for people to prove ownership, but that's the only way they're getting the coins back.

**Comment by tailsjoin** [comment]
I wasn't using a script, I copy paste my passwords (generated from /dev/urandom) from a password mananger. It would be really nice to see the irc logs because I copy/pasted straight from my terminal the commands and outputs, then we'll know for sure if it was on a recover.

You could have the possible owner sign with a deposit address. Looks like this is where the 1.5btc came from.

    945a4095e469db46f938e5f2825eb0674e996f9d6cf36102e7b1f508858a8375

**Comment by AdamISZ** [comment]
@tailsjoin OK. But this is not about passwords. It's about seed recovery. It can *only* happen when you recover from seed phrase, and only if you don't enter 12 words.

Thanks for the pointer. I thought I'd already found 0.2 of the funding txs, but anyway will check it out tomorrow.

**Comment by tailsjoin** [comment]
My seeds are also copy/pasted. So I'm guessing that day in irc I was recovering from seed and for some reason my clipboard was blank and I pasted nothing to generate this seed. Which I imported, rescanned, and then reattempted the recovery which was successful. Seems like the most likely scenario with what we now know.

**Comment by tailsjoin** [comment]
This is the only other tx I have coming into the 4fec1c wallet:

    c888103c051a4403446071bd75b2ae50ca28ffaeb3f67308c68f630c77fa91ec

**Comment by AdamISZ** [comment]
I believe this can be closed.
