### ISSUE TITLE
Creation of multiple copies of orders can skew probabilities

### ISSUE THREAD

**Issue by AdamISZ** [chris-belcher/joinmarket#197]
It's a well understood issue with the system that offers placed in the orderbook by makers are not enforced to be real. This is connected with the oft-discussed related issues of whether we want to use persistent identities, and whether snooping to gain info on utxos might link join outputs( #156 ). The connection between the two being that utxos have to be *announced*; if they're announced "early" we lose privacy, if they're announced "late" (as they are today) we regain privacy but have no certainty that offers represent real coins.

I'm not attempting to answer all these questions here, but that just gives context to the following:

The [choose order code](https://github.com/chris-belcher/joinmarket/blob/master/lib/common.py#L409-L429) leaves open a possibility of skewing the probability of selection in favour of a particular maker. It ensures that each chosen order is from a separate counterparty, but only after  having chosen the order from the full list via the chooseOrdersFunc. Thus, if a maker just announces multiple copies of each of his orders, any probabilistic choice will favour him for doing so (e.g. weighted_orders_choose).

If the code were altered to prevent this, there are a few decisions that need to be made about how to do that. Rejecting identical orders is a trivial one, but equally trivial coding by the antisocial maker could sidestep it. A hard limit on the number of orders per maker is another possibility.

However, even if this change was made, the basic problem remains: it only requires a little ingenuity on the part of an antisocial maker to run multiple bots off the same wallet, perhaps disguising the orders to make them look different. It doesn't work "out of the box" for sure, but it equally clearly can be done. I don't think we can "fix" this without revisiting the issues mentioned in the first paragraph.

**Comment by chris-belcher** [comment]
Yet another way to fix this would be to only consider one order per maker in the weighted probability chooser.

This is kind of how it works now (though voluntarily, in a way that can be gamed) where the publicly released yield generator algorithms have min/max sizes that dont overlap, so the weighted_choose_order code only ends up with one-order-per-maker for any cj_amount.

**Comment by AdamISZ** [comment]
Rather late revisit, but anyway..

> Yet another way to fix this would be to only consider one order per maker in the weighted probability chooser.

Well, yes, I said that "A hard limit on the number of orders per maker is another possibility." And I agree that this is the most practical first cut decision. But the other concern, the deeper one, remains (see last paragraph and, I guess, first).

I'm revisiting it because looking at the orderbook I see at least one (and prob. more) makers gaming the system this way. I might try to put together a PR to enforce one order consideration per maker.

**Comment by chris-belcher** [comment]
My intuition says the only-one-order-per-maker is easy to do. Maybe using the SQL DISTINCT keyword or something.

**Comment by AdamISZ** [comment]
@chris-belcher  Yes, it's not hard. Did you look at the PR?

**Comment by AdamISZ** [comment]
This was merged (and fixed twice after :) )
