### ISSUE TITLE
Sweep orders are not scalable in current form

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#204]
A nick came into the IRC channel saying he was trying to do a sweep transaction but got a MemoryError, his log showed it crashed during the itertools.combinations() call. Simple maths really, 80 choose 7 is 3 billion. Still odd why doesn't everyone crash when trying this.

We can exclude a lot of orders at the start.

We don't know the cj_amount, but we know its lower than total_amount so can exclude minsize > total_amount.
We can choose orders to use individually like the non-sweep algorithm does, then calculate the cj_amount at the end. If one of the orders happens to not have the right minsize/maxsize range, discard it, keep looping until all orders are in range.

That should go a long way to making this scale for hundreds or thousands of makers.

**Comment by chris-belcher** [comment]
In general we should use the SQL functions as much as possible.

**Comment by tailsjoin** [comment]
I have serious lag until I kill the process when I do more than `-N 3` on a sweep. This happens on all of my machines. I'm sure some hardware would crash easily.

**Comment by tailsjoin** [comment]
This person on reddit couldn't do an `-N 5` sweep with 12gb of ram.

https://www.reddit.com/r/joinmarket/comments/3m3ipf/memoryerror_using_sendpaymentpy/

**Comment by chris-belcher** [comment]
fixed https://github.com/chris-belcher/joinmarket/commit/aa319fbf13fcf299b3aeb9f794161c39cecae841
