### ISSUE TITLE
is there a simple logfile showing stats for yield-generator?

### ISSUE THREAD

**Issue by dooglus** [chris-belcher/joinmarket#215]
I'd like to see a logfile showing just the following per transaction:

    spent outputs, new inputs, profit for transaction

and the following each time a transaction is seen:

    my confirmed, unconfirmed, and total balance per level, and confirmed, unconfirmed and total balance summed over all levels

Running `python wallet-tool.py wallet.json` shows me my "total balance" but it doesn't include any of the unconfirmed transactions and so is always less than I started with.

Does such a thing exist? If not, would you merge such a pull request?

**Comment by chris-belcher** [comment]
How is this different from the existing yigen-statement.csv file ?

I dont mind too much if you edit it since #200 is a much better way of doing things as it gets its information from the blockchain.
