### ISSUE TITLE
wallet gaps

### ISSUE THREAD

**Issue by dooglus** [chris-belcher/joinmarket#223]
I see m/0/0/0/038 and m/0/0/0/039 in my wallet were never used, but m/0/0/0/040 was.

Checking the code, it looks like the index is incremented every time a new join is proposed, even if the maker never publishes his final transaction.

This seems to open up a DoS vector. He can simply request many joins and never publish them, resulting in very large 'gaps' in the HD wallet and effectively causing us to "lose" our outputs.

**Comment by AdamISZ** [comment]
It's to prevent snooping: otherwise, proposing a join is enough to know what the maker's output addresses will be.

**Comment by dooglus** [comment]
Fair enough.

**Comment by tailsjoin** [comment]
Still a DOS vector, no?

**Comment by dooglus** [comment]
Yes.

**Comment by chris-belcher** [comment]
Not a DOS, it was fixed here https://github.com/chris-belcher/joinmarket/commit/b3dc7c7291a38183324175326dcf70eedadb3861 by having the wallet class store the current index in the wallet file. If you restore from seed you may need to increase the gap limit (as described in the wiki)
