### ISSUE TITLE
notify missing bind option

### ISSUE THREAD

**Issue by JulianTosh** [chris-belcher/joinmarket#231]
I'm running joinmarket on its own host, separate from the bitcoin node.

Notifications from the bitcoin node cannot reach the notify socket on the joinmarket node because the notify process binds to 127.0.0.1:62602.

There should be a notify_bind option, along with the notify_port option in joinmarket.cfg, to specify a specific (routable) IP address.

A temporary work around is to redirect the tcp connections with:  

```
ncat --sh-exec "ncat 127.0.0.1 62602" -l $(hostname -i) 62602 --keep-open
```

**Comment by chris-belcher** [comment]
I agree.

As well as doing adding this https://github.com/chris-belcher/joinmarket/blob/master/lib/blockchaininterface.py#L387-L399 the wiki should also be edited to document this.

**Comment by JulianTosh** [comment]
Updated wiki. I will remove the "future implementation" when this issue is closed.

**Comment by chris-belcher** [comment]
https://github.com/chris-belcher/joinmarket/commit/e5a666bd5c961c042a90d308a3d3c4f046ae3cce
