### ISSUE TITLE
tumbler.py vs sendpayment.py

### ISSUE THREAD

**Issue by JulianTosh** [chris-belcher/joinmarket#234]
Can you correct any misconceptions I have regarding tumbler and sendpayment please?

* Tumbler mixes all internal wallet funds, or at least from a specific mixing level, with market maker funds, and sends the entire available internal balance to multiple destination addresses, which may/can/should exist in different wallets, internally (joinmarket's wallet.json) and externally (mycelium/blockchain/electrum/etc).

* sendpayment is basically the same thing as tumbler, but allows you to specify a specific amount to send and you can only specify a single destination address.

* Is there any other feature/function I'm missing?

**Comment by tailsjoin** [comment]
Tumbler does multiple sendpayments with randomized wait times, amounts, and makers per tx. Destination addresses can be in any wallet. The important thing is to not recombine tumbled funds into the same outputs.

**Comment by JulianTosh** [comment]
Thanks for the sanity check!
