### ISSUE TITLE
Tumbler.py exception "not enough funds"

### ISSUE THREAD

**Issue by JulianTosh** [chris-belcher/joinmarket#236]
Questions:

Q1: When tumbler.py throws this exception, is there any chance it will recover or otherwise proceed with tumbling?

Q2: I have not yet had a single tumbler attempt work after many many tries. So if I keep doing one tumbler coinjoin at a time for 3-4 times (with the expectation that they will all continue to fail after a single coinjoin), will I effectively have tumbled coins with no link to previous coins?

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "tumbler.py", line 188, in run
    self.send_tx(tx, self.balance_by_mixdepth[tx['srcmixdepth']], sweep)
  File "tumbler.py", line 148, in send_tx
    utxos = self.taker.wallet.select_utxos(tx['srcmixdepth'], total_amount)
  File "/home/joinmarket/workspace/joinmarket/lib/common.py", line 253, in select_utxos
    inputs = self.utxo_selector(unspent, amount)
  File "/home/joinmarket/workspace/joinmarket/lib/bitcoin/transaction.py", line 451, in select
    raise Exception("Not enough funds")
Exception: Not enough funds
```

Logs: http://pastebin.com/M1xn9FyR

**Comment by chris-belcher** [comment]
Q1: There is no chance it will recover.

Q2: Yes. If you do enough repeated coinjoins then you will *probably* unlink your addresses.

BTW the log appears to be the same one as from here https://github.com/chris-belcher/joinmarket/issues/235 It has the error "killing taker, TODO handle this error"

**Comment by JulianTosh** [comment]
My apologies for the incorrect log file.

There is the correct one.

http://pastebin.com/JGNgPjQr

**Comment by JulianTosh** [comment]
I will be pulling 235 and trying again. thanks.
