### ISSUE TITLE
Synchronization with Bitcoin Core fails with JsonRpcConnectionError

### ISSUE THREAD

**Issue by stardrifter** [chris-belcher/joinmarket#242]
When trying to test integration with Bitcoin Core, using "python wallet-tool.py wallet.json" (as per https://github.com/chris-belcher/joinmarket/wiki/Running-JoinMarket-with-Bitcoin-Core-full-node#running--checking-it-works) all I get is this:

```
Enter wallet decryption passphrase: 
[2015/09/27 23:30:58] requesting wallet history
[2015/09/27 23:31:09] rpc: getaddressesbyaccount ['joinmarket-wallet-6fbffc']
[2015/09/27 23:31:09] rpc: listtransactions ['joinmarket-wallet-6fbffc', 1000, 0, True]
[2015/09/27 23:31:20] rpc: listunspent []
Traceback (most recent call last):
  File "wallet-tool.py", line 54, in <module>
    common.bc_interface.sync_wallet(wallet)
  File "/home/gregorius/Projects/ext/joinmarket/lib/blockchaininterface.py", line 81, in sync_wallet
    self.sync_unspent(wallet)
  File "/home/gregorius/Projects/ext/joinmarket/lib/blockchaininterface.py", line 510, in sync_unspent
    unspent_list = self.rpc('listunspent', [])
  File "/home/gregorius/Projects/ext/joinmarket/lib/blockchaininterface.py", line 432, in rpc
    res = self.jsonRpc.call(method, args)
  File "/home/gregorius/Projects/ext/joinmarket/lib/jsonrpc.py", line 106, in call
    response = self.queryHTTP (request)
  File "/home/gregorius/Projects/ext/joinmarket/lib/jsonrpc.py", line 95, in queryHTTP
    raise JsonRpcConnectionError ("JSON-RPC connection failed. Err:" + repr(exc))
jsonrpc.JsonRpcConnectionError: JSON-RPC connection failed. Err:UnicodeDecodeError('utf8', '\xc5', 0, 1, 'unexpected end of data')
```

This happens every time I try. I have followed https://github.com/chris-belcher/joinmarket/wiki/Running-JoinMarket-with-Bitcoin-Core-full-node to the letter (although I am not using bitcoind, but rather bitcoin-qt, so I did "bitcoin-qt -datadir=/mnt/home2/gregorius/.bitcoin -rescan").

Here's how my joinmarket.cfg looks like:

```

[BLOCKCHAIN]
blockchain_source = bitcoin-rpc 
#options: blockr, bitcoin-rpc, json-rpc, regtest
#for instructions on bitcoin-rpc read https://github.com/chris-belcher/joinmarket/wiki/Running-JoinMarket-with-Bitcoin-Core-full-node 
network = mainnet
rpc_host = localhost
rpc_port = 8332
rpc_user = blah
rpc_password = h4Nr6l5ImX8rSWMgXVY5xPpeuuI9

[MESSAGING]
#host = irc.cyberguerrilla.org
channel = joinmarket-pit
#port = 6697
#usessl = true
#socks5 = false
socks5_host = localhost
socks5_port = 9150
#for tor
host = 6dvj6v5imhny3anf.onion
port = 6697
usessl = true
socks5 = true
maker_timeout_sec = 30

[POLICY]
#for dust sweeping, try merge_algorithm = gradual
merge_algorithm = default
```

I am using Tor, but I specified port as 9150, as the one exposed by TorBrowser.
Here's my bitcoin.conf (sitting in /mnt/home2/gregorius/.bitcoin so it definitely gets loaded by bitcoin-qt):

```
# bitcoin.conf configuration file. Lines beginning with # are comments.

# JSON-RPC options (for controlling a running Bitcoin/bitcoind process)
 
# server=1 tells Bitcoin-QT to accept JSON-RPC commands.
server=1
 
# You must set rpcuser and rpcpassword to secure the JSON-RPC api
rpcuser=blah
rpcpassword=h4Nr6l5ImX8rSWMgXVY5xPpeuuI9

# Joinmarket
walletnotify=curl -sI --connect-timeout 1 http://localhost:62602/walletnotify?%s
alertnotify=curl -sI --connect-timeout 1 http://localhost:62602/alertnotify?%s
```

I am running:
JoinMarket f29707cba940cc8ccdf4cc629f0b0c29bd11ea49
bitcoin-qt (Bitcoin Core version v0.11.0.0-gd26f951 (64-bit)) over Tor
Ubuntu 14.04 64bit

I will be more than happy to provide you with any further info you need.

Best regards,
Stardrifter

**Comment by chris-belcher** [comment]
what version of python do you have? JoinMarket runs on python2

    python --version

**Comment by stardrifter** [comment]
```
$ python --version
Python 2.7.6
```

**Comment by chris-belcher** [comment]
Have you used bitcoin-qt for other stuff?

Looks like calling getaddressesbyaccount and listtransactions works for you, it only crashes on listunspent. So maybe your wallet contains other non-joinmarket addresses and transactions and there's something funny about them. If so, could you run listunspent in the debug console or with bitcoin-cli and see if there's anything a bit strange with encoding. Maybe characters from another language in the labels.

If that's the problem as a workaround you could rename your wallet.dat and allow bitcoin core to create a new empty wallet.dat for joinmarket.

**Comment by stardrifter** [comment]
```Maybe characters from another language in the labels```
I think that might be the case. I have no way of checking that now, but I will verify that in the evening.

As a side note: if that's really the source of my problem, I would be quite surprised, as I thought that Ubuntu should use UTF8 by default, and this is where I put the label on my transaction.

**Comment by chris-belcher** [comment]
python can be a bit funny about encoding.

**Comment by stardrifter** [comment]
It turned out, that BitCoin Core v0.11.0.0-gd26f951 has problems with properly encoding some higher, not basic Latin characters in it's RPC interface. All these chars present fine on GUI, but not so in RPC.
When I called listunspent from debug console, in the "account" field of the response I got things like:
* "�\u009A" for "Ś" character
* "�\u0085" for "ą" character
* "ż" for "ż" character

As you can see "ż" is encoded properly, while the others are not.
When I edited this transaction label, to get rid of all these "high" chars, wallet-tool.py ran just fine. Now, I can start enjoying joinmarket.
I will be filling a bug with BitCoin team. Thanks a lot for your swift responses and helpful suggestions!
