### ISSUE TITLE
orderbook.json

### ISSUE THREAD

**Issue by the9ull** [chris-belcher/joinmarket#256]
Hello,
do you think that adding the possibility to export a json version of the orderbook to the ob-watcher.py it is useful? It could semplify/encourage external script of analyze it.

I wrote the code but I'll commit it only if it is useful.

**Comment by adlai** [comment]
:+1:

**Comment by CohibAA** [comment]
I think this could be a useful tool. +1

**Comment by chris-belcher** [comment]
Yes I agree. I was thinking of some API exposed like this.

There could be a nice IRC bot like gribble that can print out parameters of the orderbook, also the prices could be shown on the subreddit header like usd/btc is on /r/bitcoinmarkets
