### ISSUE TITLE
Signing code.

### ISSUE THREAD

**Issue by tailsjoin** [chris-belcher/joinmarket#271]
I think it is a good idea to sign releases now that you have a donation address coded in. Besides the fact that it is just good practice. I'm not sure what would be the easiest solution for you: tags, releases, tars, etc., but I think it's important.

**Comment by chris-belcher** [comment]
It's a good idea. Most importantly since the code hold people's money so they should be able to verify it hasn't been modified in transit.

Probably tagging releases on github is the best way. I'm currently working on this issue https://github.com/chris-belcher/joinmarket/issues/61 so after that I think a release is good. We could include install scripts that set up everything easily.

**Comment by chris-belcher** [comment]
Also https://github.com/chris-belcher/joinmarket/issues/116 is also pretty essential to any respectable JoinMarket release. Funny how nobody on social media has yet noticed that JoinMarket uses a centralized messaging channel which could by halted straight away by the single communist operator who runs cyberguerrilla IRC. Of course we'd regroup and find somewhere else, but still.

It will probably take too long wait for all these features before releasing a signed codebase. Maybe it's better to sign a tarball now, or release with a warning that it's only alpha software and be prepared for downtime and/or to update quickly when asked.

**Comment by petertodd** [comment]
Wladimir made a good best practices writeup for Bitcoin Core development: http://www.mail-archive.com/bitcoin-development@lists.sourceforge.net/msg05467.html

**Comment by chris-belcher** [comment]
Thanks for the link @petertodd very helpful.

Signed this https://github.com/chris-belcher/joinmarket/commit/4dd52c0b9248f55eb731189cb9db4e6757ce1247
If I understand right, as git commits are a chain of hashes, this one signed commit should verify all the ones behind it?

Key is: https://pgp.mit.edu/pks/lookup?op=get&search=0xEF734EA677F31129
Fingerprint: 0A8B 038F 5E10 CC27 89BF CFFF EF73 4EA6 77F3 1129
https://twitter.com/chris_belcher_/status/559879313622061056 https://bitcointalk.org/index.php?action=profile;u=321816

**Comment by petertodd** [comment]
Thanks! Just checked and the signatures look good to me. Good to get your key signed by a few more people of course, but this gets you 90% of the way there.

>  If I understand right, as git commits are a chain of hashes, this one signed commit should verify all the ones behind it?

Exactly!

**Comment by tailsjoin** [comment]
Closing.
