### ISSUE TITLE
add watchonly addresses to Bitcoin Core on demand

### ISSUE THREAD

**Issue by dooglus** [chris-belcher/joinmarket#275]
Currently 50 watchonly addresses are added to Bitcoin Core at startup, and then no more are added as they are needed, resulting in Core losing track of its unspent outputs.

It would be better if watchonly addresses were added as they were used, rather than an arbitrary number like 50 being used, since 50 is too many for some users and not enough for others.

(I guess this is what the 'TODO' in `lib/blockchaininterface.py` is referring to as well, but not it isn't only when we broadcast transactions that we need to do this - it's also if we share signatures made using addresses which aren't yet in the Core wallet):

    #TODO must add the tx addresses as watchonly if case we ever broadcast a tx
    # with addresses not belonging to us

**Comment by chris-belcher** [comment]
I did that here. https://github.com/chris-belcher/joinmarket/commit/7317866acd8e472dc6ed23d9e765a28b62be4981

**Comment by dooglus** [comment]
Nice.
