### ISSUE TITLE
Not enough liquidity

### ISSUE THREAD

**Issue by abitfan** [chris-belcher/joinmarket#281]
I'm trying to do a coinjoin for 99000 with the following properties: no absorder, txfee => 1000
I modified the code as follows:
```python
index 482d2ac..bfa8789 100644
--- a/lib/taker.py
+++ b/lib/taker.py
@@ -332,6 +332,8 @@ class OrderbookWatch(CoinJoinerPeer):
 
        def on_order_seen(self, counterparty, oid, ordertype, minsize, maxsize, txfee, cjfee):
                try:
+                       if ordertype == "absorder":
+                               return
                        if int(oid) < 0 or int(oid) > sys.maxint:
                                debug("Got invalid order ID: " + oid + " from " + counterparty)
                                return
@@ -346,7 +348,7 @@ class OrderbookWatch(CoinJoinerPeer):
                        if int(maxsize) < 0 or int(maxsize) > 21*10**14:
                                debug("Got invalid maxsize: " + maxsize + " from " + counterparty)
                                return
-                       if int(txfee) < 0:
+                       if int(txfee) < 1000:
                                debug("Got invalid txfee: " + txfee +  " from " + counterparty)
                                return
                        if int(minsize) > int(maxsize):
```

Using: sendpayment.py --rpcwallet "" 99000 btc_address 
I get:
ERROR not enough liquidity in the orderbook n=2 suitable-counterparties=0 amount=99000 totalorders=0
ERROR not enough liquidity in the orderbook, exiting

By inspecting the orderbook it seems this coinjoin is doable. Any ideas ?

**Comment by chris-belcher** [comment]
What are you trying to do? Why does your code drop all absorders ?

I dont see anything in the orderbook that is a relative-fee order, has a miner fee contribution of more than 1000 satoshi and has a min/maxsize that includes the range 99000 satoshi.

**Comment by abitfan** [comment]
My bad, I didn't realize the limiting factor was minsize. Sorry for the noise.
