### ISSUE TITLE
New default dust threshold: Bitcoin Core v0.11.1

### ISSUE THREAD

**Issue by tailsjoin** [chris-belcher/joinmarket#288]
Old default dust threshold was 546, it is now 2730 satoshi by default. Should we suggest a change to bitcoin.conf defaults or adjust it in the code? I think adjusting the code is needed.

**Comment by tailsjoin** [comment]
https://github.com/chris-belcher/joinmarket/pull/289

**Comment by chris-belcher** [comment]
We should read and understand the discussion here https://github.com/bitcoin/bitcoin/pull/6793 to understand the direction that Bitcoin Core is taking. I think the idea of a dust threshold will be phased out from Core.

Right now in JoinMarket this value is used only to stop outputs being created of that size.

**Comment by tailsjoin** [comment]
Closing: https://github.com/chris-belcher/joinmarket/commit/96d8696381e3e272061f807a48ebf3633d164be5
