### ISSUE TITLE
This code will crash if newabs=oldabs=[]

### ISSUE THREAD

**Issue by AdamISZ** [chris-belcher/joinmarket#310]
https://github.com/chris-belcher/joinmarket/blob/new-yieldgen-algo/yield-generator.py#L189-L198

Posting as a sanity check; if you agree @chris-belcher I will make PR.

This arose from discussions with a yieldgen who set txfee=0 on new-yieldgen-algo and consequently had minsize=0 and so had no absorders, and had a crash. From the log it looked very much like a crash in the unconfirm callback thread, leading me eventually to look at this.

**Comment by chris-belcher** [comment]
Looks ok to me, nice find.
