### ISSUE TITLE
No PGP signatures on repo

### ISSUE THREAD

**Issue by petertodd** [chris-belcher/joinmarket#319]
There's no tags yet, so no signed tags. Additionally the commits themselves aren't signed. Right now, we're trusting github when we use joinmarket!

Wladimir made a good best practices writeup for Bitcoin Core development: http://www.mail-archive.com/bitcoin-development@lists.sourceforge.net/msg05467.html

**Comment by tailsjoin** [comment]
https://github.com/chris-belcher/joinmarket/issues/271

**Comment by petertodd** [comment]
Thanks, closing.
