### ISSUE TITLE
Fresh pull, JoinMarket unusable.

### ISSUE THREAD

**Issue by tailsjoin** [chris-belcher/joinmarket#322]
I'm sorry, but these instructions for usage are way too invasive:

https://github.com/chris-belcher/joinmarket/blob/master/INSTALL_UBUNTU.md

Basically everything after running the install script is beyond acceptable. I can't even use JM is this state. I have to revert now.

You cannot expect users to be polluting their bashrc with variables like this.

**Comment by AdamISZ** [comment]
Is simply exporting those variables in the shell acceptable? If not, could you explain why? 

Is that the only part that's a problem, or is there something else that results in you saying "I can't even use JM in this state"?

**Comment by fivepiece** [comment]
@tailsjoin , the instruction to use `~/.bashrc` for placing the exports is not a must.  You can set these exports wherever you'd like (`~/dotfiles/jm_env` for example) and source them only when needed.

The process is meant to be least invasive as possible, as all dependencies and build products are kept contained within the joinmarket home folder. The matter of exports was described in a "generic" way and is left for the discretion of the user. Do let me know if you think there's a cleaner way though, I'm very interested.

Thanks.

**Comment by AdamISZ** [comment]
@chris-belcher when you're about, I suggest rolling back this secp256k1 update and just keeping a copy of the branch separately as @tailsjoin has suggested. Too many complaints.

Please continue the conversation above though, I'd like to know how we should do it better.

**Comment by tailsjoin** [comment]
I'm not sure how to do it better as I'm currently working on a disaster completely separate from JM for now, but I know I don't have to do this with with any other software I run. So there must be a less invasive method.

**Comment by fivepiece** [comment]
@tailsjoin a pretty way to do that is to put all these exports into a file in `~/dotfiles/jm.env` , then create a `yield-generator.sh` file in `~/bin/`, and have it run something like `source ~/dotfiles/jm.env && python ${joinmarket_home}/yield-generator.py`

**Comment by mb300sd** [comment]
I agree with @fivepiece, thats about what I did, just make wrapper scripts for the joinmarket files and set the variables in there.

**Comment by mb300sd** [comment]
Playing around with it a little more, I've got it as

apt-get install libffi6 python-pexpect python-pycparser libsodium-dev libffi-dev
pip install cffi

which should take care of all the dependencies except secp256k1.

**Comment by tailsjoin** [comment]
Closing. Reverted, but I'm not finding the link because the maintainers seems to have given up and it's rubbing off on me.

**Comment by AdamISZ** [comment]
@mb300sd 
> I'm using system libsecp256k1

sorry, I don't follow? This isn't available yet right. As for (lib)secp256k1 being available in a standard way, we'll have to wait for an official release. I have a vague impression it will be quite soon (considering Core 0.12)

**Comment by mb300sd** [comment]
@AdamISZ 

Not available in any packages, but "make install" works.

**Comment by AdamISZ** [comment]
Ah OK, sure.
