### ISSUE TITLE
Separation of secret data

### ISSUE THREAD

**Issue by AdamISZ** [chris-belcher/joinmarket#4]
Just an idea:

Enforce some encapsulation of private data in such a way that it's impossible that later coding errors lead to involuntary leaking of it.

**Comment by chris-belcher** [comment]
What exactly do you mean?

**Comment by AdamISZ** [comment]
What prompted this was the fact that console dumps show seeds and keys.

**Comment by chris-belcher** [comment]
https://github.com/chris-belcher/joinmarket/commit/f30209684d80d877d14992c57a7e82cb711b4613
