### ISSUE TITLE
encrypting() method in irclib renamed

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#43]
To a more descriptive name. Perhaps get_encryption_box() or get_encryption_object()

Let's not do it right now, every time there's a commit I need to merge it into my msgchan branch.

**Comment by AdamISZ** [comment]
ACK

**Comment by chris-belcher** [comment]
Done https://github.com/chris-belcher/joinmarket/commit/42530c2f37bdb3a98b425535e6abbaaf03f866ce
