### ISSUE TITLE
Remove keyfile

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#5]
As far as I can tell, there is no need for the keyfile. Keys in libsodium do not have to be persistent across different instances, since its all authenticated.

The keyfile clutters up the working directory and requires an extra command line argument in some cases.

**Comment by AdamISZ** [comment]
Agreed.

Just one counterpoint though: it would give an opportunity for persistence of identity (authentication is with btc signatures, but that's only per-transaction). Whether such persistence might have any value, I don't know.

I'll do a PR to remove it.
