### ISSUE TITLE
Check authentication of encryption

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#59]
At some point the authentication of the encryption between peers must be checked. I've noticed some apparently unfinished things.

E.G.
https://github.com/chris-belcher/joinmarket/blob/4b935e2d89a9e8d646836bbb4c15bc86ec7bb74d/taker.py#L38

signing_btc_add and signing_btc_pub don't seem to be used anywhere after that

**Comment by AdamISZ** [comment]
I think it's a hangover from an earlier version of the code. The authentication is done in auth_counterparty using the coinjoin pubkey. I'll take another look shortly.

**Comment by AdamISZ** [comment]
Indeed, the taker's authentication request is here: https://github.com/chris-belcher/joinmarket/blob/4b935e2d89a9e8d646836bbb4c15bc86ec7bb74d/taker.py#L47-L52

Those declarations can be deleted.

The steps are listed in encryption_protocol.txt.

**Comment by chris-belcher** [comment]
https://github.com/chris-belcher/joinmarket/commit/bd3a6fec323aadf1f3bca3cf69f5e139182bfe5d
