### ISSUE TITLE
Orderbook Watch doesnt delete orders when a maker is kicked

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#60]
to reproduce

run gui-taker.py
local its page in your browser
kick a yield generator
reload the page
note the orders of the kicked bot are still there

**Comment by abitfan** [comment]
I'm not able to replicate this. Seems to work as expected.

**Comment by chris-belcher** [comment]
Apparently I fixed it here and forgot to close this. https://github.com/chris-belcher/joinmarket/commit/a4ba0a5d96a8e8e24353266ebf8c955a6f2c66c0#diff-fc8ffb45857c1b6539f3506c6c16a515R350

By the way abitfan do you have an email address / way to contact?
