### ISSUE TITLE
Implement socks5 proxy 

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#63]
This code is needed so that Tor or an ssh tunnel can be used.

The configuration should go in the joinmarket.cfg file.

Should be a fairly easy addition for keen contributers.

**Comment by abitfan** [comment]
Unfortunately snoonet doesn't allow tor either:
:ny.snoonet.org NOTICE 1NYAADB2S :*** You're banned! For instructions on how to appeal this ban please visit snoonet.org/banappeal.
ERROR :Closing link: (unknown@xxx.xxx.xxx.xxx) [Z-Lined: Hello WitoldZak,you have a host listed in the Dan.me.uk Torexit database. For more information, visit https://www.dan.me.uk/torcheck with your IP: xxx.xxx.xxx.xxx (ID: L1G627MVX6)]
Connection closed by foreign host.
