### ISSUE TITLE
IRC server won't allow Tor connections

### ISSUE THREAD

**Issue by dreboli** [chris-belcher/joinmarket#76]
Running tumble.py on Whonix gives:
```
starting tumbler
connecting to irc
connecting
>>pubmsg !orderbook
waiting for all orders to certainly arrive
Connected to IRC and joined channel
line was zero length
disconnected irc
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "tumbler.py", line 170, in run
    relorder_fee = float(orders[0])
IndexError: list index out of range

connecting
SSLError(8, '_ssl.c:504: EOF occurred in violation of protocol')
AttributeError("'NoneType' object has no attribute 'close'",)
disconnected irc
```

with usessl = false in joinmarket.cfg the output is:
```
starting tumbler
connecting to irc
connecting
line was zero length
disconnected irc
connecting
line was zero length
disconnected irc
```

**Comment by chris-belcher** [comment]
IRC servers usually ban Tor exit nodes, you have to connect to their onion.

Also it seems the snoonet onion recently went down and they haven't gotten it up yet. Go ask in their main channel (but dont mention joinmarket)

**Comment by BitpopCoin** [comment]
Pretty sad, one of their sysops died a few months back https://www.snoonet.org/updates/26-in-remembrance-of-edify

**Comment by Erock23175** [comment]
Alright which rabbit hole am I going to have to climb down to "get" this conversation?

**Comment by dreboli** [comment]
Is there a way to use joinmarket through Tor?

**Comment by chris-belcher** [comment]
Right now no, I've been looking around for IRC networks which allow tor as somewhere to move the pit to. Obviously that's a priority.

Also this is all temporary until another messaging channel that isnt IRC is coded.

**Comment by BitpopCoin** [comment]
What's an alternative to irc?

**Comment by chris-belcher** [comment]
https://github.com/cpacia/Subspace

Or maybe tox

**Comment by BitpopCoin** [comment]
I wonder if this is open source http://www.bleep.pm

**Comment by adlai** [comment]
@BitpopCoin It's not.

**Comment by chris-belcher** [comment]
With commit https://github.com/chris-belcher/joinmarket/commit/6dbe42ba8f424539424b7b8ecee5631d605ff1f1 we move to an IRC server that allows tor
