### ISSUE TITLE
JoinMarket should generate the default config file

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#79]
Have no config file in the repo. When joinmarket is run and doesnt detect a config file have it create the default one. Also add joinmarket.cfg to .gitignore

New users get a default config file without any attention, old users dont get their modified config file overwritten by git

Would solve the problem highlighted here
https://github.com/chris-belcher/joinmarket/pull/77

**Comment by BitpopCoin** [comment]
Good. Unfortunately I only know php, not python so I can't help.

**Comment by K1773R** [comment]
and we need documentation. otherwise the old users will miss out on the new settings

**Comment by chris-belcher** [comment]
The wiki page has documentation https://github.com/chris-belcher/joinmarket/wiki/Configuring-with-joinmarket.cfg

**Comment by abitfan** [comment]
This was implemented and can be closed.
