### ISSUE TITLE
Reproduce numpy.random.choice and similar small functions

### ISSUE THREAD

**Issue by chris-belcher** [chris-belcher/joinmarket#85]
Seems a bit overkill to require the entire numpy package when we just use one function, which could be replicated fairly easily. Code segments could probably be found on stackexchange

slowaes is a small module and could be distributed alongside too, electrum and tlsnotary already do this

EDIT: actually, tumbler.py also has some numpy random stuff

**Comment by AdamISZ** [comment]
You could add the socks module to the list, I think. It's just one socks.py file.

**Comment by K1773R** [comment]
@AdamISZ agree, setting the SOCKS5 header for a connection is really simple, just some chr's.

**Comment by chris-belcher** [comment]
tumbler.py uses numpy.random.normal() numpy.random.power() numpy.random.exponential()

**Comment by chris-belcher** [comment]
I have added slowaes.py and socks.py to joinmarket https://github.com/chris-belcher/joinmarket/commit/7a82abc1234667de0627663b65b57187084c9375

**Comment by chris-belcher** [comment]
Just found out all the random functions we use from numpy are actually found in python random too, which is included by default.

https://docs.python.org/2/library/random.html

**Comment by AdamISZ** [comment]
Done in #186
