### ISSUE TITLE
TypeError: choose_order() takes exactly 4 arguments (3 given)

### ISSUE THREAD

**Issue by dreboli** [chris-belcher/joinmarket#86]
$python tumbler.py -x 0.003 -w 30 wallet.json address1 address2
...
tumble with these tx? (y/n):y
Enter wallet decryption passphrase: 
[] downloading wallet history
...
connected to IRC
...
coinjoining 2423423424
**Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "tumbler.py", line 189, in run
    self.send_tx(tx, self.balance_by_mixdepth[tx['srcmixdepth']], sweep)
  File "tumbler.py", line 136, in send_tx
    orders, total_cj_fee = choose_order(self.taker.db, amount, tx['makercount'])
TypeError: choose_order() takes exactly 4 arguments (3 given)**

**Comment by chris-belcher** [comment]
Thanks for the bug report, that was a stupid one where the simple checks were forgotten.
