### ISSUE TITLE
Cannot make it work with bitcoin core

### ISSUE THREAD

**Issue by enkumber** [chris-belcher/joinmarket#95]
This is what I get: 

python wallet-tool.py wallet.json
Enter wallet decryption passphrase: 
[2015/05/28 16:13:00] requesting wallet history
[2015/05/28 16:13:07] rpc: ['bitcoin-cli', '-datadir=/mnt/The\\', 'Archive/bitcoincore', 'getaddressesbyaccount', 'joinmarket-wallet-9b917a']
Traceback (most recent call last):
  File "wallet-tool.py", line 54, in <module>
    common.bc_interface.sync_wallet(wallet)
  File "/home/ciprian/joinmarket-master/lib/blockchaininterface.py", line 31, in sync_wallet
    self.sync_addresses(wallet)
  File "/home/ciprian/joinmarket-master/lib/blockchaininterface.py", line 386, in sync_addresses
    imported_addr_list = json.loads(self.rpc(['getaddressesbyaccount', wallet_name]))
  File "/home/ciprian/joinmarket-master/lib/blockchaininterface.py", line 365, in rpc
    res = subprocess.check_output(self.command_params + args)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

What am I doing wrong ?

**Comment by AdamISZ** [comment]
You need to add the path to `bitcoin-cli` to your PATH variable.

**Comment by enkumber** [comment]
I thought I did:

bitcoin_cli_cmd = bitcoin-cli -datadir=/mnt/The\ Archive/bitcoincore

**Comment by K1773R** [comment]
@enkumber spaces in folder names are always a bad thing. still, bitcoin-cli cant be found in your $PATH, so either adjust your $PATH or create a symbolic link to bitcoin-cli inside a folder of $PATH.

**Comment by AdamISZ** [comment]
Yes, seems like two issues; first, bitcoin-cli not in your path, so either put it in $PATH or given absolute path in the joinmarket.cfg file (well, @K1773R gives a more complete answer)  , and second, the space in the filename for data directory. Seems the config parser can't handle that. Something we could look into at some point.

**Comment by enkumber** [comment]
sorry to ruin your time with this noob questions. i'm lookinginto it, it seems bitcoin-cli is somewhere else but I don't really know where since it's not in ~/.bitcoin/
I'm looking into it

**Comment by enkumber** [comment]
ok so it seems that I installed only bitcoin-qt. I installed bitcoin core, is this normal ?

**Comment by AdamISZ** [comment]
as long as you have 0.10 you should be OK. For me bitcoin-cli and bitcoind are in the src/ directory, but I compiled it from src. Whereever it is, it should be in the same place as the main bitcoin daemon (bitcoind).

**Comment by enkumber** [comment]
I found it and now it works. The problem now is that it doesn't show the real balance since I deposited 0.02 in /mnt/The Archive/bitcoincore/bitcoin.conf but wallet-tool reports that it has 0 btc in it ...

**Comment by AdamISZ** [comment]
Joinmarket uses (can use) bitcoin core to query the blockchain, but it has its own wallet internally. You have to put coins into joinmarket's own wallet. See the wiki guide on this.

**Comment by AdamISZ** [comment]
Also, consider using #joinmarket on freenode IRC or the reddit r/joinmarket for support questions. Github is more appropriate when there are actual issues with the software.

**Comment by enkumber** [comment]
I did this, I generated an internal wallet and I deposited in an internal address
mixing depth 0 m/0/0/
 receive addresses m/0/0/0/
  m/0/0/0/000 15ogv5iu2gtT5dDeXiwvgZAqduXgMKLoNr  new 0.00000000 btc 
  m/0/0/0/001 12joJagyvZjRZDdDsECX17AzE1MKWsegFy  new 0.00000000 btc 
  m/0/0/0/002 1D8iQcMgXmP2rbo8R8rR5Q9kh4rrz1QivJ  new 0.00000000 btc 
  m/0/0/0/003 1CAbgmLDuAxkTj8JtGhc7ZdWx4SRdRRPBm  new 0.00000000 btc 
  m/0/0/0/004 1AUv4qLXVhEosSAtn7NfQrdwASkedtw9A3  new 0.00000000 btc 
  m/0/0/0/005 1HqMgoTm9qEPEpZjz6SbvbiEzvUd8ziL4S  new 0.00000000 btc 
 change addresses m/0/0/1/
for mixdepth=0 balance=0.00000000btc

I deposited in the first one ... still the balance shows zero

**Comment by enkumber** [comment]
i didn't rescan ... now it's ok
