### ISSUE TITLE
IRC connect_attemps too low

### ISSUE THREAD

**Issue by K1773R** [chris-belcher/joinmarket#97]
This night, the IRC Servers b32 and/or onion had issues, hence connection failed.

After trying to connect 10 times, the bot exited.
This is coded in lib/irc.py L454

Should we make this configurable in the joinmarket.cfg or just remove this limit?

**Comment by enkumber** [comment]
can you connect now? it semmes I can't

**Comment by K1773R** [comment]
nope, currently its down. tough i raised connect_attempts to 1000, hence it may be able to reconnect in time...

**Comment by chris-belcher** [comment]
Remove the limit

**Comment by chris-belcher** [comment]
commited https://github.com/chris-belcher/joinmarket/commit/0ad6388b3180ae5fd62b4539d9858fca52b69d7c
